name: Java Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instala Node.js (necessário apenas para npm)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Instala dependências do npm (mesmo que não haja)
    - name: Install Node.js dependencies
      working-directory: java_spring_boot
      run: npm install

    # Setup Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Dar permissão de execução para mvnw
    - name: Give execute permission to mvnw
      working-directory: java_spring_boot
      run: chmod +x mvnw

    # Build Spring Boot project
    - name: Build Spring Boot project
      working-directory: java_spring_boot
      run: ./mvnw clean package
